Proyecto/Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProyectoApp.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('espacios/', include('espacios_obligados.urls')),
    path('datawarehouse/', include('datawarehouse.urls')),
]

Proyecto/espacios_obligados/urls.py
from django.urls import path
from . import views
import threading

urlpatterns = [
    path('registrar_entidad/', views.registrar_entidad, name='registrar_entidad'),
    path('registrar_sede/<int:entidad_id>/',
         views.registrar_sede, name='registrar_sede'),
    path('listar_sedes/<int:entidad_id>/',
         views.listar_sedes, name='listar_sedes'),
    path('listar_mis_entidades_sedes/', views.listar_mis_entidades_sedes,
         name='listar_mis_entidades_sedes'),
    path('administrar_entidad_sede/<int:sede_id>/',
         views.administrar_entidad_sede, name='administrar_entidad_sede'),
    path('editar_sede/<int:sede_id>/', views.editar_sede, name='editar_sede'),
    path('declaracion_jurada/<int:sede_id>/',
         views.declaracion_jurada, name='declaracion_jurada'),
    path('registrar_dea/<int:sede_id>/',
         views.registrar_dea, name='registrar_dea'),
    path('cargar_modelos/', views.cargar_modelos, name='cargar_modelos'),
    path('listar_deas/<int:sede_id>/', views.listar_deas, name='listar_deas'),
    path('editar_dea/<int:dea_id>/', views.editar_dea, name='editar_dea'),
    path('activar_dea/<int:dea_id>/', views.activar_dea, name='activar_dea'),
    path('desactivar_dea/<int:dea_id>/', views.desactivar_dea, name='desactivar_dea'),
    path('eliminar_dea/<int:dea_id>/', views.eliminar_dea, name='eliminar_dea'),
    path('mapa/', views.listar_deas_activos, name='mapa'),
    path('mapa_solidario/', views.listar_deas_activos_solidarios, name='mapa_solidario'),
    path('notificar_responsables/<int:sede_id>/', views.notificar_responsables, name='notificar_responsables'),
    path('registrar_servicio_dea/<int:dea_id>/', views.registrar_servicio_dea, name='registrar_servicio_dea'),
    path('listar_reparaciones_dea/<int:dea_id>/', views.listar_reparaciones_dea, name='listar_reparaciones_dea'),
    path('listar_mantenimientos_dea/<int:dea_id>/', views.listar_mantenimientos_dea, name='listar_mantenimientos_dea'),
    path('registrar_responsable/<int:sede_id>/', views.registrar_responsable, name='registrar_responsable'),
    path('listar_responsables/<int:sede_id>/', views.listar_responsables, name='listar_responsables'),
    path('editar_responsable/<int:responsable_id>/', views.editar_responsable, name='editar_responsable'),
    path('eliminar_responsable/<int:responsable_id>/', views.eliminar_responsable, name='eliminar_responsable'),
    path('solicitud_aprobacion/', views.solicitud_aprobacion, name='solicitud_aprobacion'),
    path('solicitud_aprobar/<int:solicitud_id>/', views.aprobar_solicitud, name='aprobar_solicitud'),
    path('lista_solicitudes_pendientes/', views.lista_solicitudes_pendientes, name='lista_solicitudes_pendientes'),
    path('aprobar_solicitud/<int:solicitud_id>/', views.aprobar_solicitud, name='aprobar_solicitud'),
    path('rechazar_solicitud/<int:solicitud_id>/', views.rechazar_solicitud, name='rechazar_solicitud'),

     # Certificante
    path('certificante/listado_espacios_obligados', views.listar_espacios_obligados_certificante,
         name='listar_espacios_obligados_certificante'),
     path('certificante/nueva-visita/<int:espacio_obligado_id>', views.nueva_visita, name='nueva_visita'),
     path('certificante/visitas/espacio-obligado/<int:espacio_obligado_id>', views.listar_visitas, name='listar_visitas'),
     path('certificante/visita/<int:visita_id>', views.eliminar_visita, name='eliminar_visita'),


     # Muerte Subita
     path('registrar_muerte_subita/<int:sede_id>/', views.registrar_muerte_subita, name='registrar_muerte_subita'),
     path('listar_eventos_muerte_subita/<int:sede_id>/', views.listar_eventos_muerte_subita, name='listar_eventos_muerte_subita'),
]


# Iniciar el hilo que ejecuta el planificador al iniciar la aplicación (chequeo de vencimiento de ertificaciones)
threading.Thread(target=views.run_scheduler, daemon=True).start()

Proyecto/espacios_obligados/models.py
from django.db import models
from usuarios.models import Representante, Provincias, Certificante
from django.contrib.gis.db import models as gis_models

# Create your models here.

class Entidad(models.Model):
    id = models.AutoField(primary_key=True)
    razon_social = models.CharField(max_length=200)
    cuit = models.CharField(max_length=200)
    sector = models.CharField(max_length=200)
    tipo = models.CharField(max_length=200)
    
    def __str__(self):
        return self.razon_social
    

class Sede(models.Model):
    representantes = models.ManyToManyField(Representante)
    nombre = models.CharField(max_length=200)
    cant_personas_externas = models.IntegerField(default=0)
    superficie = models.IntegerField(default=0)
    ubicacion = gis_models.PointField()
    cant_personal = models.IntegerField(default=0)
    direccion = models.CharField(max_length=200)
    responsables = models.ManyToManyField('Responsable', blank=True, related_name='responsables')
    
    # Declaración Jurada
    
    personal_capacitado = models.BooleanField(default=False)
    senaletica = models.BooleanField(default=False)
    protocolo_accion = models.BooleanField(default=False)
    sistema_emergencia = models.BooleanField(default=False)
    deas_registrados = models.ManyToManyField('DEA', blank=True)
    deas_decreto = models.IntegerField(default=0)
    provincia = models.ForeignKey(Provincias, on_delete=models.CASCADE)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)

    def __str__(self):
        return '%s , %s' % (self.nombre, self.provincia) 
    

class EspacioObligado(models.Model):
    estado = models.CharField(max_length=100,default='EN PROCESO')  # Agregando el campo estado
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE)
    motivo = models.TextField(blank=True,default='')
    fecha_creacion = models.DateField()
    def __str__(self):
        return f'!nombre sede {self.sede.nombre} y estado{self.estado}'

class DEA(models.Model):
    dea_sede = models.ForeignKey(Sede, on_delete=models.CASCADE)
    marca = models.CharField(max_length=200)
    modelo = models.CharField(max_length=200)
    numero_serie = models.CharField(max_length=200)
    nombre_representativo = models.CharField(max_length=200)
    solidario = models.BooleanField(default=False)
    estado = models.CharField(max_length=10, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo')

    def __str__(self):
        return self.nombre_representativo
    

class HistorialDEA(models.Model):
    dea = models.ForeignKey(DEA, on_delete=models.CASCADE)
    dia = models.DateField()
    servicio = models.CharField(max_length=200)
    observaciones = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.dea.nombre_representativo


class Responsable(models.Model):
    sede_asignada = models.ForeignKey(Sede, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    telefono = models.CharField(max_length=200)
    email = models.CharField(max_length=200)
    def __str__(self):
        return self.nombre + " " + self.apellido
    

class SolicitudAprobacion(models.Model):
    representante = models.ForeignKey(Representante, on_delete=models.CASCADE)
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    sede = models.ForeignKey(Sede, on_delete=models.CASCADE)
    motivo = models.TextField()
    aprobado = models.BooleanField(default=False)
    estado = models.TextField(default='', blank=True)
    def __str__(self):
        return f'nombre sede {self.sede.nombre} y estado{self.estado}'


class Visita(models.Model):
    id = models.AutoField(primary_key=True)
    fecha_hora = models.DateTimeField()
    observaciones = models.TextField()
    resultado = models.CharField(max_length=20, choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')])
    espacio_obligado_id = models.ForeignKey(EspacioObligado, on_delete=models.CASCADE)
    certificante_id = models.ForeignKey(Certificante, on_delete=models.CASCADE, null=True, blank=True)

class EventoMuerteSubita(models.Model):
    fecha = models.DateField()
    sexo = models.CharField(max_length=20, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino'), ('otro', 'Otro')])
    edad = models.IntegerField()
    fallecido = models.BooleanField(default=False)
    rcp = models.BooleanField(default=False)
    tiempo_rcp = models.IntegerField(null=True, blank=True)
    dea = models.ForeignKey(DEA, on_delete=models.CASCADE, null=True, blank=True)
    inconveniente = models.CharField(max_length=250, blank=True, null=True)
    descarga_electrica = models.BooleanField(default=False, null=True, blank=True)
    cantidad_descarga = models.IntegerField(null=True, blank=True)
    observaciones = models.TextField(null=True, blank=True)
    sede_id = models.ForeignKey(Sede, on_delete=models.CASCADE)
    representante_id = models.ForeignKey(Representante, on_delete=models.CASCADE)

Proyecto/espacios_obligados/templates/dea/editar_dea.html
{% extends "ProyectoApp/base.html" %}
{% load static %}
{% block content %}
<style>
    .form-check-input[type="checkbox"] {
        margin-left: 10px;
    }
</style>
<h1>Editar DEA</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a href="{% url 'listar_deas' sede %}" class="btn btn-primary">Atrás</a>
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>

{% endblock %}

Proyecto/espacios_obligados/templates/dea/eliminar_dea.html
{% extends "ProyectoApp/base.html" %}
{% block content %}
<h1>Eliminar DEA</h1>
<p>¿Estás seguro de que deseas eliminar el DEA "{{ dea.nombre_representativo }}"?</p>
<form method="post">
    {% csrf_token %}
    <a class="btn btn-primary" href="{% url 'listar_deas' sede_id=sede %}">Cancelar</a>
    <button type="submit" class="btn btn-danger">Eliminar</button>
</form>
{% endblock %}

Proyecto/espacios_obligados/templates/dea/listar_deas.html
{% extends "ProyectoApp/base.html" %}
{% load static %}
{% block content %}
<a href="{% url 'registrar_dea' sede.id %}" class="btn bg-gradient-cyan">Registrar Nuevo DEA</a>
<div class="card-container">
  {% for dea in deas %}
  <div class="card">
    <div class="card-header">
      <h3>{{ dea.nombre_representativo }}</h3>
    </div>
    <div class="card-body">
      <p>Marca: {{ dea.marca }}</p>
      <p>Modelo: {{ dea.modelo }}</p>
      <p>Numero de Serie: {{ dea.numero_serie }}</p>
      <p>{% if dea.solidario %} Es solidario {% else %} No es solidario {% endif %}</p>
      <hr>
      <a href="{% url 'editar_dea' dea.id %}" class="btn btn-primary">Editar</a>
      {% if dea.estado == 'activo' %}
      <a href="{% url 'desactivar_dea' dea.id %}" class="btn btn-danger">Inactivar</a>
      {% else %}
      <a href="{% url 'activar_dea' dea.id %}" class="btn btn-success">Activar</a>
      {% endif %}
      <a href="{% url 'registrar_servicio_dea' dea.id %}" class="btn btn-primary">Registrar Reparación/Mantenimiento</a>
      <a href="{% url 'listar_reparaciones_dea' dea.id %}" class="btn btn-primary">Ver Reparaciones</a>
      <a href="{% url 'listar_mantenimientos_dea' dea.id %}" class="btn btn-primary">Ver Mantenimientos</a>
      <a href="{% url 'eliminar_dea' dea.id %}" class="btn btn-danger">Eliminar</a>
    </div>
  </div>
  {% endfor %}
  <a href="{% url 'listar_mis_entidades_sedes' %}" class="btn btn-primary">Atrás</a>
</div>
{% endblock %}

Proyecto/espacios_obligados/templates/dea/listar_mantenimientos.html
{% extends "ProyectoApp/base.html" %}
{% block content %}
<h1>Listado de Mantenimientos para {{ dea.nombre_representativo }}</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
        {% for mantenimiento in mantenimientos %}
        <tr>
            <td>{{ mantenimiento.dia }}</td>
            <td>{{ mantenimiento.observaciones }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="2">No se encontraron mantenimientos</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'listar_deas' sede.id %}">Volver</a>
{% endblock %}

Proyecto/espacios_obligados/templates/dea/listar_reparaciones.html
{% extends "ProyectoApp/base.html" %}
{% block content %}
<h1>Listado de Reparaciones para {{ dea.nombre_representativo }}</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
        {% for reparacion in reparaciones %}
        <tr>
            <td>{{ reparacion.dia }}</td>
            <td>{{ reparacion.observaciones }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="2">No se encontraron reparaciones</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a class="btn btn-primary" href="{% url 'listar_deas' sede.id %}">Volver</a>
{% endblock %}

Proyecto/espacios_obligados/templates/dea/registrar_dea.html
{% extends "ProyectoApp/base.html" %}
{% block content %}
<style>
    .form-check-input[type="checkbox"] {
        margin-left: 10px;
    }
</style>
<h2>Registrar DEA</h2>

  <form method="post" id="formulario_dea">
    {% csrf_token %}
    <div>
      <label for="id_marca">Marca:</label>
      <select name="marca" id="id_marca" class="form-select form-control">
        <option value="">Selecciona una marca</option>
        {% for marca in marcas %}
          <option value="{{ marca.id }}">{{ marca.marca }}</option>
        {% endfor %}
      </select>
    </div>
    <div>
      <label for="id_modelo">Modelo:</label>
      <select name="modelo" id="id_modelo" class="form-select form-control">
        <option value="">Selecciona una marca primero</option>
      </select>
    </div>
    <div>
        <label for="id_numero_serie">Número de Serie:</label>
        <input type="text" name="numero_serie" id="id_numero_serie" class="form-control">
      </div>
      <div>
        <label for="id_nombre_representativo">Nombre Representativo:</label>
        <input type="text" name="nombre_representativo" id="id_nombre_representativo" class="form-control">
      </div>
      <div>
        <label for="id_solidario">Solidario:</label>
        <input type="checkbox" name="solidario" id="id_solidario" class="form-check-input">
      </div>

    <a href="{% url 'listar_deas' sede.id %}" class="btn btn-secondary">Volver</a>
    <button type="submit" class="btn btn-primary">Registrar DEA</button>
  </form>
  
  <script>

    function getCookie(name) {
      var cookieValue = null;
      if (document.cookie && document.cookie !== "") {
        var cookies = document.cookie.split(";");
        for (var i = 0; i < cookies.length; i++) {
          var cookie = cookies[i].trim();
          if (cookie.substring(0, name.length + 1) === name + "=") {
            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
            break;
          }
        }
      }
      return cookieValue;
    }

    document.getElementById("id_marca").addEventListener("change", function() {
      actualizarOpcionesModelo(this.value);
    });

    function actualizarOpcionesModelo(marcaSeleccionada) {
      const modeloSelect = document.getElementById("id_modelo");
      modeloSelect.innerHTML = "";

      if (marcaSeleccionada) {
        fetch('/espacios/cargar_modelos/', {
          method: 'POST',
          headers: {
            'X-CSRFToken': getCookie('csrftoken'),  // Obtén el token CSRF con la función getCookie
            'Content-Type': 'application/x-www-form-urlencoded',
          },
          body: `marca=${marcaSeleccionada}`,
        })
          .then(response => response.json())
          .then(data => {
            const modelos = data.modelos;

            modelos.forEach(function(modelo) {
              const option = document.createElement("option");
              option.text = modelo;
              option.value = modelo;
              modeloSelect.add(option);
            });
          });
      } else {
        const option = document.createElement("option");
        option.text = "Selecciona una marca primero";
        option.value = "";
        modeloSelect.add(option);
      }
    }
  </script>
</div>
{% endblock %}

Proyecto/espacios_obligados/templates/dea/registrar_servicio_dea.html
{% extends "ProyectoApp/base.html" %}
{% load static %}
{% block content %}
<style>
    .form-check-input[type="checkbox"] {
        margin-left: 10px;
    }
</style>
<h1>Registrar servicio</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <a class="btn btn-primary" href="{% url 'listar_deas' sede.id %}">Atrás</a>
    <button type="submit" class="btn btn-primary">Guardar Cambios</button>
</form>
{% endblock %}